# Generated by Django 3.2.3 on 2021-05-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productCategory',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
