# Generated by Django 3.2.3 on 2021-05-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210519_0012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
